name: Bug 反馈 (Bug Report)
description: 提交 Bug 反馈 (Bug Report)
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢你花时间填写此报告！在开始之前，我们非常推荐阅读一遍[《开源最佳实践》](https://github.com/LinuxSuRen/open-source-best-practice)，这会在很大程度上提高我们彼此的效率。
        Thanks for taking the time to fill out this bug report! 
  - type: markdown
    attributes:
      value: "## 环境信息 ( Environment)"
  - type: dropdown
    validations:
      required: true
    attributes:
      label: 系统版本 (System Version)
      description: What version of our software are you running?
      multiple: false
      options:
        - Windows10 or Windows11
        - Windows7
  - type: input
    id: app-version
    validations:
      required: true
    attributes:
      label: 软件版本 (Software version)
  - type: markdown
    attributes:
      value: "## 详细信息 (Details)"
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？ (What happened?)
      description: |
        "最好还告诉我们，你预计会发生什么。"
        "Also tell us, what did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 相关日志输出 (Relevant log output)
      description: |
        "请复制并粘贴任何相关的日志输出。 这将自动格式化为代码，因此无需反引号。"
        "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
  - type: textarea
    id: additional-information
    attributes:
      label: 附加信息 (Additional information)
      description: |
        "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
        "If you have other information to note, you can fill it in here (screenshots, videos, etc.)."
