name: Test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

permissions:
  contents: read


jobs:
  pytest:
    strategy:
      matrix:
        include:
          - os: windows-latest
            python-version: "3.9"
          - os: windows-2019
            python-version: "3.7"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python version
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Cache Python packages
      id: cache-pip
      uses: actions/cache@v3
      env:
        cache-name: cache-python-${{ matrix.python-version }}
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-${{ env.cache-name }}-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-mock -e .
        pip install -r requirements.txt
    
    - name: Test with pytest
      uses: liskin/gh-problem-matcher-wrap@v2
      with:
        linters: pytest
        run: pytest --cov=src tests
